#Build docker image using azure pipeline

pool:
  vmImage: 'ubuntu-16.04'
  
variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '4a5c5332-569e-4b6d-8376-c3d972e67bc9'
  imageRepository: 'digitalsolutionsnlnlcoviddatadashboard'
  containerRegistry: 'kpmgnlbigvwscovid19fewet01acr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

jobs:
- job: BuildandPushImage
  steps:
    - script: |
        docker build --build-arg CD_TAG="latest" --build-arg NEXT_PUBLIC_SANITY_PROJECT_ID=5mog5ask --network=host -t digitalsolutionsnlnlcoviddatadashboard:latest -f Dockerfile .

    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: '$(dockerRegistryServiceConnection)'
    - task: Docker@2
      displayName: Push an image to container registry
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'push'
        tags: 'digitalsolutionsnlnlcoviddatadashboard:latest'

