# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '4a5c5332-569e-4b6d-8376-c3d972e67bc9'
  imageRepository: 'digitalsolutionsnlnlcoviddatadashboard'
  containerRegistry: 'kpmgnlbigvwscovid19fewet01acr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: 'build'
        repository: '$(imageRepository)'
        containerRegistry: '$(dockerRegistryServiceConnection)'
        Dockerfile: '**/Dockerfile'
        tags: '1.0'
        arguments: '--build-arg NEXT_PUBLIC_SANITY_PROJECT_ID=5mog5ask --network=host'
    - task: Docker@2
      displayName: Push an image to container registry
      inputs:
        command: 'push'
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        tags: '1.0'

- stage: Scan Code
  displayName: Scan code
  jobs:  
  - job: Scan
    displayName: Scan
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: SonarCloudPrepare@1
      displayName: Build an image
      inputs:
        SonarCloud: 'covid19-dashboard'
        organization: 'innovationfactory-qa'
        scannerMode: 'MSBuild'
        projectKey: 'covid19-dashboard'
        projectName: 'covid19-dashboard'
    - task: SonarCloudAnalyze@1
    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'