
#Build docker image using azure pipeline

pool:
  vmImage: 'ubuntu-16.04'
  
variables:
  PIPELINE: 'innovationfactory.pit5'

jobs:
- job: BuildImage
  steps:
   - script: |
       docker build --build-arg CD_TAG="latest" --build-arg NEXT_PUBLIC_SANITY_PROJECT_ID=5mog5ask --network=host -f Dockerfile